using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CadastroDigital.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CadastroDigital.Domain.EntitiesConfigs
{
    public class FuncaoConfig: IEntityTypeConfiguration<Funcao>
    {
        public void Configure(EntityTypeBuilder<Funcao>builder){

            //Tabela
            builder.ToTable("Funcao");
            
            //Primary Key
            builder.HasKey(p => p.Id);

            //Index
            builder.HasIndex(i => i.CategoriaId)
            .IsUnique(false)
            .HasDatabaseName("idx_funcao_categoria");

            //Foreign Key
            builder.HasOne(f => f.Categoria)
            .WithOne(f => f.Funcao)
            .HasForeignKey<Categoria>(f => f.Id)
            .HasConstraintName("fk_funcao_categoria");
            
            //Atributos
            builder.Property(f => f.Id)
            .HasColumnName("Id")
            .ValueGeneratedOnAdd()
            .IsRequired();

            builder.Property(f => f.Codigo)
            .HasColumnName("Codigo")
            .HasMaxLength(5)
            .IsRequired(false);

            builder.Property(f => f.Descricao)
            .HasColumnName("Descricao")
            .HasMaxLength(100)
            .IsRequired();

            builder.Property(f => f.CategoriaId)
            .HasColumnName("CategoriaId")
            .ValueGeneratedNever()
            .IsRequired();
        }

        public static Funcao[] HasData(){

            return new Funcao[]{

                new Funcao(){ Id =1,Codigo = "204", Descricao = "Acompanhante Terapeutico", CategoriaId = 1},
                new Funcao(){ Id =2,Codigo = "135", Descricao = "Administrador", CategoriaId = 1},
                new Funcao(){ Id =3,Codigo = "209", Descricao = "Admnistrativo", CategoriaId = 1},
                new Funcao(){ Id =4,Codigo = "148", Descricao = "Advogado", CategoriaId = 1},
                new Funcao(){ Id =5,Codigo = "111", Descricao = "Agente Administrativo", CategoriaId = 1},
                new Funcao(){ Id =6,Codigo = "367", Descricao = "Agente Comunitário de Saúde", CategoriaId = 1},
                new Funcao(){ Id =7,Codigo = "156", Descricao = "Agente Cultural", CategoriaId = 1},
                new Funcao(){ Id =8,Codigo = "289", Descricao = "Agente de Comunicação", CategoriaId = 1},
                new Funcao(){ Id =9,Codigo = "368", Descricao = "Agente de controle endemias", CategoriaId = 1},
                new Funcao(){ Id =10,Codigo = "281", Descricao = "Agente de Portaria", CategoriaId = 1},
                new Funcao(){ Id =11,Codigo = "181", Descricao = "Agente de Zoonose", CategoriaId = 1},
                new Funcao(){ Id =12,Codigo = "167", Descricao = "Ajudante", CategoriaId = 1},
                new Funcao(){ Id =13,Codigo = "222", Descricao = "Ajudante de Cozinha", CategoriaId = 1},
                new Funcao(){ Id =14,Codigo = "93", Descricao = "Ajudante Geral", CategoriaId = 1},
                new Funcao(){ Id =15,Codigo = "159", Descricao = "Almoxarife", CategoriaId = 1},
                new Funcao(){ Id =16,Codigo = "237", Descricao = "Analista Ambiental", CategoriaId = 1},
                new Funcao(){ Id =17,Codigo = "193", Descricao = "Analista de Sistemas", CategoriaId = 1},
                new Funcao(){ Id =18,Codigo = "2", Descricao = "Aposentada", CategoriaId = 1},
                new Funcao(){ Id =19,Codigo = "92", Descricao = "Armador", CategoriaId = 1},
                new Funcao(){ Id =20,Codigo = "96", Descricao = "Arquiteto", CategoriaId = 1},
                new Funcao(){ Id =21,Codigo = "147", Descricao = "Ascensorista", CategoriaId = 1},
                new Funcao(){ Id =22,Codigo = "299", Descricao = "Ass Direção", CategoriaId = 1},
                new Funcao(){ Id =23,Codigo = "67", Descricao = "Ass. Legislativo", CategoriaId = 1},
                new Funcao(){ Id =24,Codigo = "342", Descricao = "Ass.Adm.Unid.Pr.Soc.", CategoriaId = 1},
                new Funcao(){ Id =25,Codigo = "336", Descricao = "Asses.do Gab.do Sub-pref.", CategoriaId = 1},
                new Funcao(){ Id =26,Codigo = "133", Descricao = "Assessor Executivo", CategoriaId = 1},
                new Funcao(){ Id =27,Codigo = "277", Descricao = "Assessor Parlamentar", CategoriaId = 1},
                new Funcao(){ Id =28,Codigo = "61", Descricao = "Assessor Técnico", CategoriaId = 1},
                new Funcao(){ Id =29,Codigo = "117", Descricao = "Assessor Tecnico II", CategoriaId = 1},
                new Funcao(){ Id =30,Codigo = "207", Descricao = "Assessor Tecnico III", CategoriaId = 1},
                new Funcao(){ Id =31,Codigo = "129", Descricao = "Assessor Tecnico Iv", CategoriaId = 1},
                new Funcao(){ Id =32,Codigo = "261", Descricao = "Assessora", CategoriaId = 1},
                new Funcao(){ Id =33,Codigo = "66", Descricao = "Assessora Tecnica", CategoriaId = 1},
                new Funcao(){ Id =34,Codigo = "39", Descricao = "Assistente  Presidencia", CategoriaId = 1},
                new Funcao(){ Id =35,Codigo = "353", Descricao = "Assistente do Gatl", CategoriaId = 1},
                new Funcao(){ Id =36,Codigo = "64", Descricao = "Assistente do Legislativo", CategoriaId = 1},
                new Funcao(){ Id =37,Codigo = "53", Descricao = "Assistente Legislativo", CategoriaId = 1},
                new Funcao(){ Id =38,Codigo = "122", Descricao = "Assistente Social", CategoriaId = 1},
                new Funcao(){ Id =39,Codigo = "65", Descricao = "Assistente Tecnico Iii", CategoriaId = 1},
                new Funcao(){ Id =40,Codigo = "99", Descricao = "Atend.Consultorio Dentario", CategoriaId = 1},
                new Funcao(){ Id =41,Codigo = "238", Descricao = "Atendente de Saude Bucal", CategoriaId = 1},
                new Funcao(){ Id =42,Codigo = "57", Descricao = "Atendente Legislativo", CategoriaId = 1},
                new Funcao(){ Id =43,Codigo = "197", Descricao = "Aux de Enfermagem", CategoriaId = 1},
                new Funcao(){ Id =44,Codigo = "291", Descricao = "Aux de Saude Bucal", CategoriaId = 1},
                new Funcao(){ Id =45,Codigo = "359", Descricao = "AUX DE SAUDE BUCAL", CategoriaId = 1},
                new Funcao(){ Id =46,Codigo = "324", Descricao = "Aux. de Serviços Gerais", CategoriaId = 1},
                new Funcao(){ Id =47,Codigo = "260", Descricao = "Aux. Enfermagem", CategoriaId = 1},
                new Funcao(){ Id =48,Codigo = "323", Descricao = "Aux. Serv. Gerais", CategoriaId = 1},
                new Funcao(){ Id =49,Codigo = "14", Descricao = "Aux.de Bibliotecario", CategoriaId = 1},
                new Funcao(){ Id =50,Codigo = "351", Descricao = "Aux.Operador Cinematografico", CategoriaId = 1},
                new Funcao(){ Id =51,Codigo = "157", Descricao = "Auxiliar de Adm", CategoriaId = 1},
                new Funcao(){ Id =52,Codigo = "131", Descricao = "Auxiliar de Cenografia", CategoriaId = 1},
                new Funcao(){ Id =53,Codigo = "119", Descricao = "Auxiliar de Contabilidade", CategoriaId = 1},
                new Funcao(){ Id =54,Codigo = "7", Descricao = "Auxiliar de Enfermagem", CategoriaId = 1},
                new Funcao(){ Id =55,Codigo = "191", Descricao = "Auxiliar de Laboratorio", CategoriaId = 1},
                new Funcao(){ Id =56,Codigo = "213", Descricao = "Auxiliar de Medicao", CategoriaId = 1},
                new Funcao(){ Id =57,Codigo = "338", Descricao = "Auxiliar de Plenario", CategoriaId = 1},
                new Funcao(){ Id =58,Codigo = "321", Descricao = "Auxiliar de Serviços", CategoriaId = 1},
                new Funcao(){ Id =59,Codigo = "327", Descricao = "Auxiliar de Serviços Gerais", CategoriaId = 1},
                new Funcao(){ Id =60,Codigo = "280", Descricao = "Belheteiro", CategoriaId = 1},
                new Funcao(){ Id =61,Codigo = "16", Descricao = "Bibliotecario", CategoriaId = 1},
                new Funcao(){ Id =62,Codigo = "218", Descricao = "Biologo", CategoriaId = 1},
                new Funcao(){ Id =63,Codigo = "275", Descricao = "Caefis", CategoriaId = 1},
                new Funcao(){ Id =64,Codigo = "158", Descricao = "Calceteiro", CategoriaId = 1},
                new Funcao(){ Id =65,Codigo = "219", Descricao = "Canteiro", CategoriaId = 1},
                new Funcao(){ Id =66,Codigo = "83", Descricao = "Carpinteiro", CategoriaId = 1},
                new Funcao(){ Id =67,Codigo = "210", Descricao = "Chefe Administrativo", CategoriaId = 1},
                new Funcao(){ Id =68,Codigo = "345", Descricao = "Chefe da Proc.Geral", CategoriaId = 1},
                new Funcao(){ Id =69,Codigo = "229", Descricao = "Chefe da Sespade", CategoriaId = 1},
                new Funcao(){ Id =70,Codigo = "17", Descricao = "Chefe de Departamento", CategoriaId = 1},
                new Funcao(){ Id =71,Codigo = "23", Descricao = "Chefe de Gab.do Prefeito", CategoriaId = 1},
                new Funcao(){ Id =72,Codigo = "10", Descricao = "Chefe de Seção", CategoriaId = 1},
                new Funcao(){ Id =73,Codigo = "68", Descricao = "Chefe Dep. Administracao", CategoriaId = 1},
                new Funcao(){ Id =74,Codigo = "352", Descricao = "Chefe Dep.Adm.Legislativa", CategoriaId = 1},
                new Funcao(){ Id =75,Codigo = "354", Descricao = "Chefe Dep.Ass.Legislativa", CategoriaId = 1},
                new Funcao(){ Id =76,Codigo = "343", Descricao = "Chefe Dep.Cont.Contr.Orc.", CategoriaId = 1},
                new Funcao(){ Id =77,Codigo = "320", Descricao = "Chefe Dep.Contabilidade Controle Orçamen", CategoriaId = 1},
                new Funcao(){ Id =78,Codigo = "356", Descricao = "Chefe Depto. Materias Patrimon", CategoriaId = 1},
                new Funcao(){ Id =79,Codigo = "346", Descricao = "Chefe do Gatl.", CategoriaId = 1},
                new Funcao(){ Id =80,Codigo = "40", Descricao = "Chefe Gabinete da Presidencia", CategoriaId = 1},
                new Funcao(){ Id =81,Codigo = "225", Descricao = "Chefe Na Seção de Atas", CategoriaId = 1},
                new Funcao(){ Id =82,Codigo = "62", Descricao = "Chefe Sec.de Atas", CategoriaId = 1},
                new Funcao(){ Id =83,Codigo = "330", Descricao = "Chefe Secao Redacao E Revisao", CategoriaId = 1},
                new Funcao(){ Id =84,Codigo = "6", Descricao = "Cirurgiao-dentista", CategoriaId = 1},
                new Funcao(){ Id =85,Codigo = "118", Descricao = "Contador", CategoriaId = 1},
                new Funcao(){ Id =86,Codigo = "98", Descricao = "Coopeira", CategoriaId = 1},
                new Funcao(){ Id =87,Codigo = "355", Descricao = "Coord. de Saude Bucal", CategoriaId = 1},
                new Funcao(){ Id =88,Codigo = "126", Descricao = "Coord.de Servico de Transito", CategoriaId = 1},
                new Funcao(){ Id =89,Codigo = "9", Descricao = "Coordenador II", CategoriaId = 1},
                new Funcao(){ Id =90,Codigo = "36", Descricao = "Coordenador Iii", CategoriaId = 1},
                new Funcao(){ Id =91,Codigo = "241", Descricao = "Coordenadora Pedagogico", CategoriaId = 1},
                new Funcao(){ Id =92,Codigo = "146", Descricao = "Copeira", CategoriaId = 1},
                new Funcao(){ Id =93,Codigo = "81", Descricao = "Coveiro", CategoriaId = 1},
                new Funcao(){ Id =94,Codigo = "217", Descricao = "Cozinheira", CategoriaId = 1},
                new Funcao(){ Id =95,Codigo = "132", Descricao = "Cozinheiro", CategoriaId = 1},
                new Funcao(){ Id =96,Codigo = "269", Descricao = "Dentista", CategoriaId = 1},
                new Funcao(){ Id =97,Codigo = "89", Descricao = "Desenhista", CategoriaId = 1},
                new Funcao(){ Id =98,Codigo = "88", Descricao = "Desenhista Projetista", CategoriaId = 1},
                new Funcao(){ Id =99,Codigo = "63", Descricao = "Diretor Administrativo", CategoriaId = 1},
                new Funcao(){ Id =100,Codigo = "348", Descricao = "Diretor Legislativo", CategoriaId = 1},
                new Funcao(){ Id =101,Codigo = "75", Descricao = "Diretora de Escola", CategoriaId = 1},
                new Funcao(){ Id =102,Codigo = "293", Descricao = "Economista", CategoriaId = 1},
                new Funcao(){ Id =103,Codigo = "201", Descricao = "Edei", CategoriaId = 1},
                new Funcao(){ Id =104,Codigo = "233", Descricao = "Educador de Desenvolvimento Infantil", CategoriaId = 1},
                new Funcao(){ Id =105,Codigo = "242", Descricao = "Educadora", CategoriaId = 1},
                new Funcao(){ Id =106,Codigo = "236", Descricao = "Educadora de Desenvolvimento", CategoriaId = 1},
                new Funcao(){ Id =107,Codigo = "103", Descricao = "Eletricista", CategoriaId = 1},
                new Funcao(){ Id =108,Codigo = "151", Descricao = "Encanador", CategoriaId = 1},
                new Funcao(){ Id =109,Codigo = "86", Descricao = "Encarregado", CategoriaId = 1},
                new Funcao(){ Id =110,Codigo = "154", Descricao = "Encarregado de Obras", CategoriaId = 1},
                new Funcao(){ Id =111,Codigo = "179", Descricao = "Enfermeira", CategoriaId = 1},
                new Funcao(){ Id =112,Codigo = "22", Descricao = "Enfermeiro", CategoriaId = 1},
                new Funcao(){ Id =113,Codigo = "72", Descricao = "Engenheiro", CategoriaId = 1},
                new Funcao(){ Id =114,Codigo = "220", Descricao = "Engenheiro Agronomo", CategoriaId = 1},
                new Funcao(){ Id =115,Codigo = "80", Descricao = "Escriturario", CategoriaId = 1},
                new Funcao(){ Id =116,Codigo = "52", Descricao = "Esp.Ed.I-assist. de Diretor", CategoriaId = 1},
                new Funcao(){ Id =117,Codigo = "28", Descricao = "Esp.Ed.I-assist.de Direcao", CategoriaId = 1},
                new Funcao(){ Id =118,Codigo = "20", Descricao = "Esp.Ed.I-coord. Pedagogico", CategoriaId = 1},
                new Funcao(){ Id =119,Codigo = "19", Descricao = "Esp.Ed.I-orient.Educacional", CategoriaId = 1},
                new Funcao(){ Id =120,Codigo = "29", Descricao = "Esp.Ed.Ii-diretor de Escola", CategoriaId = 1},
                new Funcao(){ Id =121,Codigo = "27", Descricao = "Esp.Ed.Ii-diretor de Unidade Escola", CategoriaId = 1},
                new Funcao(){ Id =122,Codigo = "15", Descricao = "Esp.Ed.Iii-superv.de Ensino", CategoriaId = 1},
                new Funcao(){ Id =123,Codigo = "290", Descricao = "Especialista de Educação I", CategoriaId = 1},
                new Funcao(){ Id =124,Codigo = "224", Descricao = "Especialista Em Ed.", CategoriaId = 1},
                new Funcao(){ Id =125,Codigo = "240", Descricao = "Especialista Em Edu", CategoriaId = 1},
                new Funcao(){ Id =126,Codigo = "160", Descricao = "Estofador", CategoriaId = 1},
                new Funcao(){ Id =127,Codigo = "211", Descricao = "Farmaceutico", CategoriaId = 1},
                new Funcao(){ Id =128,Codigo = "55", Descricao = "Faxineira", CategoriaId = 1},
                new Funcao(){ Id =129,Codigo = "134", Descricao = "Feitor", CategoriaId = 1},
                new Funcao(){ Id =130,Codigo = "87", Descricao = "Ferreiro", CategoriaId = 1},
                new Funcao(){ Id =131,Codigo = "3", Descricao = "Fiscal", CategoriaId = 1},
                new Funcao(){ Id =132,Codigo = "44", Descricao = "Fiscal de Iptu", CategoriaId = 1},
                new Funcao(){ Id =133,Codigo = "8", Descricao = "Fiscal de Obras", CategoriaId = 1},
                new Funcao(){ Id =134,Codigo = "314", Descricao = "Fiscal de Posturas Municipais", CategoriaId = 1},
                new Funcao(){ Id =135,Codigo = "116", Descricao = "Fiscal de Transito", CategoriaId = 1},
                new Funcao(){ Id =136,Codigo = "4", Descricao = "Fiscal de Trib.Municipais", CategoriaId = 1},
                new Funcao(){ Id =137,Codigo = "174", Descricao = "Fisioterapeuta", CategoriaId = 1},
                new Funcao(){ Id =138,Codigo = "60", Descricao = "Folha de Pagamento", CategoriaId = 1},
                new Funcao(){ Id =139,Codigo = "175", Descricao = "Fonoaudiologo", CategoriaId = 1},
                new Funcao(){ Id =140,Codigo = "54", Descricao = "Funcionario Publico", CategoriaId = 1},
                new Funcao(){ Id =141,Codigo = "137", Descricao = "Funileiro", CategoriaId = 1},
                new Funcao(){ Id =142,Codigo = "340", Descricao = "Garagista", CategoriaId = 1},
                new Funcao(){ Id =143,Codigo = "112", Descricao = "Guarda", CategoriaId = 1},
                new Funcao(){ Id =144,Codigo = "189", Descricao = "Guarda Ferramentas", CategoriaId = 1},
                new Funcao(){ Id =145,Codigo = "114", Descricao = "Guarda Municipal", CategoriaId = 1},
                new Funcao(){ Id =146,Codigo = "161", Descricao = "Guarda Municipal 2", CategoriaId = 1},
                new Funcao(){ Id =147,Codigo = "95", Descricao = "Guarda Municipal I", CategoriaId = 1},
                new Funcao(){ Id =148,Codigo = "97", Descricao = "Guarda Municipal II", CategoriaId = 1},
                new Funcao(){ Id =149,Codigo = "127", Descricao = "Guarda Municipal Iii-inspetor", CategoriaId = 1},
                new Funcao(){ Id =150,Codigo = "113", Descricao = "Guarda Municipal Iv-inspetor Chefe", CategoriaId = 1},
                new Funcao(){ Id =151,Codigo = "200", Descricao = "Guarda Munucipal", CategoriaId = 1},
                new Funcao(){ Id =152,Codigo = "364", Descricao = "Guarda Vidas", CategoriaId = 1},
                new Funcao(){ Id =153,Codigo = "208", Descricao = "Historiador", CategoriaId = 1},
                new Funcao(){ Id =154,Codigo = "358", Descricao = "iluminador", CategoriaId = 1},
                new Funcao(){ Id =155,Codigo = "239", Descricao = "Inspetor Ambiental", CategoriaId = 1},
                new Funcao(){ Id =156,Codigo = "30", Descricao = "Inspetor de Alunos", CategoriaId = 1},
                new Funcao(){ Id =157,Codigo = "180", Descricao = "Inspetor de Zoonoses", CategoriaId = 1},
                new Funcao(){ Id =158,Codigo = "296", Descricao = "Inspetora", CategoriaId = 1},
                new Funcao(){ Id =159,Codigo = "199", Descricao = "Inspetora de Aluno", CategoriaId = 1},
                new Funcao(){ Id =160,Codigo = "121", Descricao = "Inspetora de Alunos", CategoriaId = 1},
                new Funcao(){ Id =161,Codigo = "366", Descricao = "Interprete de Libras", CategoriaId = 1},
                new Funcao(){ Id =162,Codigo = "108", Descricao = "Jardineiro", CategoriaId = 1},
                new Funcao(){ Id =163,Codigo = "140", Descricao = "Jornalista", CategoriaId = 1},
                new Funcao(){ Id =164,Codigo = "166", Descricao = "Letrista", CategoriaId = 1},
                new Funcao(){ Id =165,Codigo = "110", Descricao = "Lubrificador", CategoriaId = 1},
                new Funcao(){ Id =166,Codigo = "162", Descricao = "M. Eletricista", CategoriaId = 1},
                new Funcao(){ Id =167,Codigo = "115", Descricao = "Marceneiro", CategoriaId = 1},
                new Funcao(){ Id =168,Codigo = "185", Descricao = "Mecanico", CategoriaId = 1},
                new Funcao(){ Id =169,Codigo = "5", Descricao = "Medico", CategoriaId = 1},
                new Funcao(){ Id =170,Codigo = "216", Descricao = "Medico Veterinario", CategoriaId = 1},
                new Funcao(){ Id =171,Codigo = "196", Descricao = "Medico-clinica Gera", CategoriaId = 1},
                new Funcao(){ Id =172,Codigo = "252", Descricao = "Medico-otopedia", CategoriaId = 1},
                new Funcao(){ Id =173,Codigo = "153", Descricao = "Mensageiro", CategoriaId = 1},
                new Funcao(){ Id =174,Codigo = "120", Descricao = "Merendeira", CategoriaId = 1},
                new Funcao(){ Id =175,Codigo = "125", Descricao = "Mestre", CategoriaId = 1},
                new Funcao(){ Id =176,Codigo = "82", Descricao = "Mestre Auxiliar", CategoriaId = 1},
                new Funcao(){ Id =177,Codigo = "168", Descricao = "Mjotorista", CategoriaId = 1},
                new Funcao(){ Id =178,Codigo = "149", Descricao = "Monitor de Ballet", CategoriaId = 1},
                new Funcao(){ Id =179,Codigo = "171", Descricao = "Monitor de Creche", CategoriaId = 1},
                new Funcao(){ Id =180,Codigo = "143", Descricao = "Monitor de Educ.Musical", CategoriaId = 1},
                new Funcao(){ Id =181,Codigo = "123", Descricao = "Monitor de Educacao", CategoriaId = 1},
                new Funcao(){ Id =182,Codigo = "33", Descricao = "Motorista", CategoriaId = 1},
                new Funcao(){ Id =183,Codigo = "362", Descricao = "MOTORISTA", CategoriaId = 1},
                new Funcao(){ Id =184,Codigo = "231", Descricao = "Musico Instrumentista", CategoriaId = 1},
                new Funcao(){ Id =185,Codigo = "1", Descricao = "Não definida", CategoriaId = 1},
                new Funcao(){ Id =186,Codigo = "202", Descricao = "Nspetora de Aluno", CategoriaId = 1},
                new Funcao(){ Id =187,Codigo = "150", Descricao = "Nutricionista", CategoriaId = 1},
                new Funcao(){ Id =188,Codigo = "212", Descricao = "Of.Admnistrativo", CategoriaId = 1},
                new Funcao(){ Id =189,Codigo = "31", Descricao = "Oficial  Administrativo", CategoriaId = 1},
                new Funcao(){ Id =190,Codigo = "138", Descricao = "Oficial Adm", CategoriaId = 1},
                new Funcao(){ Id =191,Codigo = "332", Descricao = "Oficial Adm.", CategoriaId = 1},
                new Funcao(){ Id =192,Codigo = "232", Descricao = "Oficial Administração", CategoriaId = 1},
                new Funcao(){ Id =193,Codigo = "145", Descricao = "Oficial Administrativo", CategoriaId = 1},
                new Funcao(){ Id =194,Codigo = "300", Descricao = "Oficial de  Administração", CategoriaId = 1},
                new Funcao(){ Id =195,Codigo = "279", Descricao = "Oficial de Adm", CategoriaId = 1},
                new Funcao(){ Id =196,Codigo = "303", Descricao = "Oficial de Adm.", CategoriaId = 1},
                new Funcao(){ Id =197,Codigo = "128", Descricao = "Oficial de Administração", CategoriaId = 1},
                new Funcao(){ Id =198,Codigo = "223", Descricao = "Oficial de Admistração", CategoriaId = 1},
                new Funcao(){ Id =199,Codigo = "183", Descricao = "Oficial de Controle Animal", CategoriaId = 1},
                new Funcao(){ Id =200,Codigo = "278", Descricao = "Oficial de Gabinete", CategoriaId = 1},
                new Funcao(){ Id =201,Codigo = "49", Descricao = "Oficial de Seguranca", CategoriaId = 1},
                new Funcao(){ Id =202,Codigo = "35", Descricao = "Oficial de Segurança", CategoriaId = 1},
                new Funcao(){ Id =203,Codigo = "34", Descricao = "Oficial Legislativo", CategoriaId = 1},
                new Funcao(){ Id =204,Codigo = "302", Descricao = "Oficila de Administração", CategoriaId = 1},
                new Funcao(){ Id =205,Codigo = "142", Descricao = "Operador de Maquinas Pesadas", CategoriaId = 1},
                new Funcao(){ Id =206,Codigo = "192", Descricao = "Operador de Som", CategoriaId = 1},
                new Funcao(){ Id =207,Codigo = "47", Descricao = "Operador Radiofonico", CategoriaId = 1},
                new Funcao(){ Id =208,Codigo = "172", Descricao = "Operador Social", CategoriaId = 1},
                new Funcao(){ Id =209,Codigo = "305", Descricao = "Operadora Social", CategoriaId = 1},
                new Funcao(){ Id =210,Codigo = "226", Descricao = "Oprrador Social", CategoriaId = 1},
                new Funcao(){ Id =211,Codigo = "163", Descricao = "Orient.Estac.Regulamentado", CategoriaId = 1},
                new Funcao(){ Id =212,Codigo = "152", Descricao = "Orient.Tec.Administrativo", CategoriaId = 1},
                new Funcao(){ Id =213,Codigo = "190", Descricao = "Orientador de Estac. Regulamentado", CategoriaId = 1},
                new Funcao(){ Id =214,Codigo = "258", Descricao = "Orientadora", CategoriaId = 1},
                new Funcao(){ Id =215,Codigo = "234", Descricao = "Pedagoga", CategoriaId = 1},
                new Funcao(){ Id =216,Codigo = "339", Descricao = "Pedagogo", CategoriaId = 1},
                new Funcao(){ Id =217,Codigo = "79", Descricao = "Pedreiro", CategoriaId = 1},
                new Funcao(){ Id =218,Codigo = "361", Descricao = "pensionista", CategoriaId = 1},
                new Funcao(){ Id =219,Codigo = "337", Descricao = "Pescador", CategoriaId = 1},
                new Funcao(){ Id =220,Codigo = "335", Descricao = "Pesquisador", CategoriaId = 1},
                new Funcao(){ Id =221,Codigo = "48", Descricao = "Pesquisador Legislativo", CategoriaId = 1},
                new Funcao(){ Id =222,Codigo = "91", Descricao = "Pintor", CategoriaId = 1},
                new Funcao(){ Id =223,Codigo = "184", Descricao = "Pintor de Autos", CategoriaId = 1},
                new Funcao(){ Id =224,Codigo = "322", Descricao = "Portaria", CategoriaId = 1},
                new Funcao(){ Id =225,Codigo = "182", Descricao = "Porteiro", CategoriaId = 1},
                new Funcao(){ Id =226,Codigo = "165", Descricao = "Pres.Comissao Perm.de Licitacoes", CategoriaId = 1},
                new Funcao(){ Id =227,Codigo = "341", Descricao = "Presidente da Comlic", CategoriaId = 1},
                new Funcao(){ Id =228,Codigo = "45", Descricao = "Procurador", CategoriaId = 1},
                new Funcao(){ Id =229,Codigo = "46", Descricao = "Procurador Geral do Municipio", CategoriaId = 1},
                new Funcao(){ Id =230,Codigo = "350", Descricao = "Procurador(a)", CategoriaId = 1},
                new Funcao(){ Id =231,Codigo = "297", Descricao = "Prof Adjunto", CategoriaId = 1},
                new Funcao(){ Id =232,Codigo = "283", Descricao = "Prof de Educ Especial", CategoriaId = 1},
                new Funcao(){ Id =233,Codigo = "106", Descricao = "Prof de Educacao Fisica", CategoriaId = 1},
                new Funcao(){ Id =234,Codigo = "32", Descricao = "Prof de Educação Infantil", CategoriaId = 1},
                new Funcao(){ Id =235,Codigo = "245", Descricao = "Prof Educaç Especial", CategoriaId = 1},
                new Funcao(){ Id =236,Codigo = "282", Descricao = "Prof Sub de Educ Infantil", CategoriaId = 1},
                new Funcao(){ Id =237,Codigo = "295", Descricao = "Prof Substituta Ens Fund II", CategoriaId = 1},
                new Funcao(){ Id =238,Codigo = "270", Descricao = "Prof. Ed. Infantil", CategoriaId = 1},
                new Funcao(){ Id =239,Codigo = "271", Descricao = "Prof. Subs. de Ensino Fundamental II", CategoriaId = 1},
                new Funcao(){ Id =240,Codigo = "37", Descricao = "Prof.de Educacao Especial", CategoriaId = 1},
                new Funcao(){ Id =241,Codigo = "243", Descricao = "Prof.de Ensino Fundamental I", CategoriaId = 1},
                new Funcao(){ Id =242,Codigo = "141", Descricao = "Prof.de Jovens E Adultos", CategoriaId = 1},
                new Funcao(){ Id =243,Codigo = "105", Descricao = "Prof.Educ.Fisica", CategoriaId = 1},
                new Funcao(){ Id =244,Codigo = "13", Descricao = "Prof.Educ.Infantil", CategoriaId = 1},
                new Funcao(){ Id =245,Codigo = "349", Descricao = "Prof.Educacao Musical", CategoriaId = 1},
                new Funcao(){ Id =246,Codigo = "18", Descricao = "Prof.Ens.Fund.I", CategoriaId = 1},
                new Funcao(){ Id =247,Codigo = "77", Descricao = "Prof.Ens.Fund.II", CategoriaId = 1},
                new Funcao(){ Id =248,Codigo = "244", Descricao = "Prof.Ensino Fundamental I", CategoriaId = 1},
                new Funcao(){ Id =249,Codigo = "301", Descricao = "Prof.Subs.de Educ.Infantil", CategoriaId = 1},
                new Funcao(){ Id =250,Codigo = "263", Descricao = "Prof.Subst.de Ensino Fundamental", CategoriaId = 1},
                new Funcao(){ Id =251,Codigo = "274", Descricao = "Prof.Subst.Educ.Especial", CategoriaId = 1},
                new Funcao(){ Id =252,Codigo = "188", Descricao = "Prof.Subst.Educ.Infantil", CategoriaId = 1},
                new Funcao(){ Id =253,Codigo = "262", Descricao = "Prof.Subst.Ens.Fund.I", CategoriaId = 1},
                new Funcao(){ Id =254,Codigo = "227", Descricao = "Prof.Subst.Ens.Fund.II", CategoriaId = 1},
                new Funcao(){ Id =255,Codigo = "294", Descricao = "Prof.Substituto Ensino", CategoriaId = 1},
                new Funcao(){ Id =256,Codigo = "286", Descricao = "Profª Subst. de Ensino", CategoriaId = 1},
                new Funcao(){ Id =257,Codigo = "104", Descricao = "Professor", CategoriaId = 1},
                new Funcao(){ Id =258,Codigo = "329", Descricao = "Professor Adjunto I", CategoriaId = 1},
                new Funcao(){ Id =259,Codigo = "284", Descricao = "Professor Adjunto II", CategoriaId = 1},
                new Funcao(){ Id =260,Codigo = "287", Descricao = "Professor de Educaçao Basica", CategoriaId = 1},
                new Funcao(){ Id =261,Codigo = "139", Descricao = "Professor de Educação Fisica", CategoriaId = 1},
                new Funcao(){ Id =262,Codigo = "273", Descricao = "Professor Educação Basica II", CategoriaId = 1},
                new Funcao(){ Id =263,Codigo = "285", Descricao = "Professor Fundamentalii", CategoriaId = 1},
                new Funcao(){ Id =264,Codigo = "307", Descricao = "Professor Substituto", CategoriaId = 1},
                new Funcao(){ Id =265,Codigo = "74", Descricao = "Professora", CategoriaId = 1},
                new Funcao(){ Id =266,Codigo = "325", Descricao = "Professora  Adjunto I", CategoriaId = 1},
                new Funcao(){ Id =267,Codigo = "326", Descricao = "Professora Adjunta Ed Infantil", CategoriaId = 1},
                new Funcao(){ Id =268,Codigo = "84", Descricao = "Professora de Educação Basica I", CategoriaId = 1},
                new Funcao(){ Id =269,Codigo = "155", Descricao = "Professora de Ensino Fundamental", CategoriaId = 1},
                new Funcao(){ Id =270,Codigo = "248", Descricao = "Professora Ed Basica I", CategoriaId = 1},
                new Funcao(){ Id =271,Codigo = "256", Descricao = "Professora Ed Infantil", CategoriaId = 1},
                new Funcao(){ Id =272,Codigo = "78", Descricao = "Professora Ed.Infantil", CategoriaId = 1},
                new Funcao(){ Id =273,Codigo = "257", Descricao = "Professora Ens. Funda II", CategoriaId = 1},
                new Funcao(){ Id =274,Codigo = "272", Descricao = "Professora Ensino Basico", CategoriaId = 1},
                new Funcao(){ Id =275,Codigo = "51", Descricao = "Professora Fund I", CategoriaId = 1},
                new Funcao(){ Id =276,Codigo = "76", Descricao = "Professora Fundamental I", CategoriaId = 1},
                new Funcao(){ Id =277,Codigo = "292", Descricao = "Professora Subst.de Ensino", CategoriaId = 1},
                new Funcao(){ Id =278,Codigo = "298", Descricao = "Professora Substituta", CategoriaId = 1},
                new Funcao(){ Id =279,Codigo = "26", Descricao = "Psicologo", CategoriaId = 1},
                new Funcao(){ Id =280,Codigo = "100", Descricao = "Readaptada-merendeira", CategoriaId = 1},
                new Funcao(){ Id =281,Codigo = "334", Descricao = "Recenseador", CategoriaId = 1},
                new Funcao(){ Id =282,Codigo = "331", Descricao = "Recenseador Auxiliar", CategoriaId = 1},
                new Funcao(){ Id =283,Codigo = "177", Descricao = "Recepcionista", CategoriaId = 1},
                new Funcao(){ Id =284,Codigo = "176", Descricao = "Recepcionista Bilingue", CategoriaId = 1},
                new Funcao(){ Id =285,Codigo = "247", Descricao = "Recepcionista-chefe de Administrativo", CategoriaId = 1},
                new Funcao(){ Id =286,Codigo = "306", Descricao = "Scretario de Unidade Escolar", CategoriaId = 1},
                new Funcao(){ Id =287,Codigo = "21", Descricao = "Sec de Unidade Escolar", CategoriaId = 1},
                new Funcao(){ Id =288,Codigo = "11", Descricao = "Secret. de Unidade Escolar", CategoriaId = 1},
                new Funcao(){ Id =289,Codigo = "214", Descricao = "Secretaria de Unidade Escolar", CategoriaId = 1},
                new Funcao(){ Id =290,Codigo = "249", Descricao = "Secretaria Unid Escolar", CategoriaId = 1},
                new Funcao(){ Id =291,Codigo = "144", Descricao = "Secretario Municipal", CategoriaId = 1},
                new Funcao(){ Id =292,Codigo = "344", Descricao = "Sem Cargo", CategoriaId = 1},
                new Funcao(){ Id =293,Codigo = "56", Descricao = "Serviços Gerais", CategoriaId = 1},
                new Funcao(){ Id =294,Codigo = "124", Descricao = "Soldador", CategoriaId = 1},
                new Funcao(){ Id =295,Codigo = "230", Descricao = "Sonoplasta", CategoriaId = 1},
                new Funcao(){ Id =296,Codigo = "164", Descricao = "Superv.Estac.Regulamentado", CategoriaId = 1},
                new Funcao(){ Id =297,Codigo = "357", Descricao = "Supervisora", CategoriaId = 1},
                new Funcao(){ Id =298,Codigo = "333", Descricao = "Tec Aux Adm", CategoriaId = 1},
                new Funcao(){ Id =299,Codigo = "43", Descricao = "Tec Auxiliar Legislativo", CategoriaId = 1},
                new Funcao(){ Id =300,Codigo = "312", Descricao = "Tec de Enfermagem", CategoriaId = 1},
                new Funcao(){ Id =301,Codigo = "198", Descricao = "Tec de Laboratorio", CategoriaId = 1},
                new Funcao(){ Id =302,Codigo = "70", Descricao = "Tec de Som", CategoriaId = 1},
                new Funcao(){ Id =303,Codigo = "360", Descricao = "tec legislativo", CategoriaId = 1},
                new Funcao(){ Id =304,Codigo = "12", Descricao = "Tec.Aux.de Adm.", CategoriaId = 1},
                new Funcao(){ Id =305,Codigo = "73", Descricao = "Tec.de Abastecimento", CategoriaId = 1},
                new Funcao(){ Id =306,Codigo = "215", Descricao = "Tec.de Apar.E Instrum.Med.E Odontol", CategoriaId = 1},
                new Funcao(){ Id =307,Codigo = "194", Descricao = "Tec.de Higiene Dental", CategoriaId = 1},
                new Funcao(){ Id =308,Codigo = "102", Descricao = "Tec.de Imobilizacao Ortopedica", CategoriaId = 1},
                new Funcao(){ Id =309,Codigo = "130", Descricao = "Tec.de Seguranca do Trabalho", CategoriaId = 1},
                new Funcao(){ Id =310,Codigo = "310", Descricao = "Tecnica de Enfermagen", CategoriaId = 1},
                new Funcao(){ Id =311,Codigo = "266", Descricao = "Tecnica Imobilização Ortopedica", CategoriaId = 1},
                new Funcao(){ Id =312,Codigo = "309", Descricao = "Técnico  de Enfermagen", CategoriaId = 1},
                new Funcao(){ Id =313,Codigo = "41", Descricao = "Tecnico Auxiliar Legislativo", CategoriaId = 1},
                new Funcao(){ Id =314,Codigo = "235", Descricao = "Tecnico de Abastecimento", CategoriaId = 1},
                new Funcao(){ Id =315,Codigo = "221", Descricao = "Tecnico de Aparelhos Biomedicos", CategoriaId = 1},
                new Funcao(){ Id =316,Codigo = "107", Descricao = "Tecnico de Contabilidade", CategoriaId = 1},
                new Funcao(){ Id =317,Codigo = "265", Descricao = "Tecnico de Enfermagem", CategoriaId = 1},
                new Funcao(){ Id =318,Codigo = "250", Descricao = "Técnico de Enfermagem", CategoriaId = 1},
                new Funcao(){ Id =319,Codigo = "308", Descricao = "Tecnico de Enfermagen", CategoriaId = 1},
                new Funcao(){ Id =320,Codigo = "268", Descricao = "Tecnico de Imobilizacao Ortopedica", CategoriaId = 1},
                new Funcao(){ Id =321,Codigo = "363", Descricao = "tecnico de informatica", CategoriaId = 1},
                new Funcao(){ Id =322,Codigo = "173", Descricao = "Tecnico de Laboratorio", CategoriaId = 1},
                new Funcao(){ Id =323,Codigo = "276", Descricao = "Tecnico de Nutricao", CategoriaId = 1},
                new Funcao(){ Id =324,Codigo = "267", Descricao = "Tecnico de Protese Dentaria", CategoriaId = 1},
                new Funcao(){ Id =325,Codigo = "254", Descricao = "Tecnico de Radiologia", CategoriaId = 1},
                new Funcao(){ Id =326,Codigo = "178", Descricao = "Tecnico de Raio X", CategoriaId = 1},
                new Funcao(){ Id =327,Codigo = "50", Descricao = "Tecnico de Som", CategoriaId = 1},
                new Funcao(){ Id =328,Codigo = "365", Descricao = "tecnico desportivo", CategoriaId = 1},
                new Funcao(){ Id =329,Codigo = "42", Descricao = "Tecnico Legislativo", CategoriaId = 1},
                new Funcao(){ Id =330,Codigo = "69", Descricao = "Telefonista", CategoriaId = 1},
                new Funcao(){ Id =331,Codigo = "203", Descricao = "Telefonista Gabinete", CategoriaId = 1},
                new Funcao(){ Id =332,Codigo = "169", Descricao = "Terapeuta Ocupacional", CategoriaId = 1},
                new Funcao(){ Id =333,Codigo = "109", Descricao = "Topografo", CategoriaId = 1},
                new Funcao(){ Id =334,Codigo = "347", Descricao = "Tratador de Animais", CategoriaId = 1},
                new Funcao(){ Id =335,Codigo = "264", Descricao = "Veterinaria", CategoriaId = 1},
                new Funcao(){ Id =336,Codigo = "85", Descricao = "Vidraceiro", CategoriaId = 1},
                new Funcao(){ Id =337,Codigo = "59", Descricao = "Xerox", CategoriaId = 1},
                new Funcao(){ Id =338,Codigo = "", Descricao = "Procurador", CategoriaId = 2},
                new Funcao(){ Id =339,Codigo = "", Descricao = "Economista ", CategoriaId = 2},
                new Funcao(){ Id =340,Codigo = "", Descricao = "Administrador", CategoriaId = 2},
                new Funcao(){ Id =341,Codigo = "", Descricao = "Administrador de Rede Pleno", CategoriaId = 2},
                new Funcao(){ Id =342,Codigo = "", Descricao = "Contador", CategoriaId = 2},
                new Funcao(){ Id =343,Codigo = "", Descricao = "Jornalista ", CategoriaId = 2},
                new Funcao(){ Id =344,Codigo = "", Descricao = "Revisor", CategoriaId = 2},
                new Funcao(){ Id =345,Codigo = "", Descricao = "Assessor Técnico", CategoriaId = 2},
                new Funcao(){ Id =346,Codigo = "", Descricao = "Engenheiro", CategoriaId = 2},
                new Funcao(){ Id =347,Codigo = "", Descricao = "Analista Jurídico", CategoriaId = 2},
                new Funcao(){ Id =348,Codigo = "", Descricao = "Analista Financeiro", CategoriaId = 2},
                new Funcao(){ Id =349,Codigo = "", Descricao = "Analista Ambiental", CategoriaId = 2},
                new Funcao(){ Id =350,Codigo = "", Descricao = "Analista Urbano", CategoriaId = 2},
                new Funcao(){ Id =351,Codigo = "", Descricao = "Técnico Legislativo", CategoriaId = 2},
                new Funcao(){ Id =352,Codigo = "", Descricao = "Técnico em Tecnologia da Informação", CategoriaId = 2},
                new Funcao(){ Id =353,Codigo = "", Descricao = "Oficial Legislativo", CategoriaId = 2},
                new Funcao(){ Id =354,Codigo = "", Descricao = "Recepcionista", CategoriaId = 2},
                new Funcao(){ Id =355,Codigo = "", Descricao = "Técnico de Som", CategoriaId = 2},
                new Funcao(){ Id =356,Codigo = "", Descricao = "Oficial de Segurança ", CategoriaId = 2},
                new Funcao(){ Id =357,Codigo = "", Descricao = "Telefonista ", CategoriaId = 2},
                new Funcao(){ Id =358,Codigo = "", Descricao = "Atendente Legislativo", CategoriaId = 2},
                new Funcao(){ Id =359,Codigo = "", Descricao = "Zelador", CategoriaId = 2},
                new Funcao(){ Id =360,Codigo = "", Descricao = "Faxineiro", CategoriaId = 2},
                new Funcao(){ Id =361,Codigo = "", Descricao = "Garçom", CategoriaId = 2}
            };
        }
    }
}